### ISSUE TITLE
missing derived channels for historic data

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-edge-ws#16]
I just pulled up some data from Feb 24, 2015 in Plots.  There is no data for D, delta-F, X, Y, or Z (as well as Dist, SQ, and SV).  Is there going to be some effort to recompute these channels for historic data?

**Comment by hasimpson-usgs** [comment]
Closing this.   This is a data issue,  not a software issue.  
It should probably be added to the agenda for Tim's meetings.  Or brought up during a monday meeting.  
geomag-algorithms already has the capability to do it.

**Comment by cafinn-usgs** [comment]
Tim's meetings with whom?
