### ISSUE TITLE
Web service error when requesting full day of 1-second data

### ISSUE THREAD

**Issue by dcstewart-usgs** [usgs/geomag-edge-ws#18]
Web service requests for a full day of 4-element 1-second data returns an error, e.g.,

http://dev-geomag.cr.usgs.gov/ws/edge/?id=BOU&starttime=2016-07-01T00:00:00Z&endtime=2016-07-01T23:59:59Z&elements=H,E,Z,F&sampling_period=1

The maximum retrievable timespan for 4 elements is about 23:51, or about 343,440 samples.

**Comment by jmfee-usgs** [comment]
Appears to have been fixed by https://github.com/usgs/geomag-edge-ws/releases/tag/v0.2.0
