### ISSUE TITLE
list of valid elements

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-edge-ws#8]
Can we add a list of "valid elements", like you have for the list of valid observatories?  I already found that I can access data for H and D (though not shown as choices).  Shouldn't I also be able to access DeltaF, SQ, SV, and Dist (and maybe others)?

**Comment by cafinn-usgs** [comment]
Per Hal, The currently supported elements are H,E,D,X,Y,Z,F,G, SQ,SV,DIST, DST.

**Comment by cafinn-usgs** [comment]
And SQN, SQE, MQN, MQE (for e-field data)

**Comment by jmfee-usgs** [comment]
v0.3.2 has been deployed, and lists valid elements.  In addition, `E-E` and `E-N` aliases have been added that, combined with `sampling_period`, map to the corresponding SQ or MQ channel names.
https://geomag.usgs.gov/ws/edge/

Directly requesting EDGE channel names is still advanced usage, and requires extra precautions to ensure the requested channel names are appropriate for the requested sampling period (which defaults to minute).
